main:
  - name: Blog
    identifier: blog
  - name: Streamers
    identifier: streamers
  - name: Tirzah "LoveSudoNimh" Grant
    identifier: lovesudonimh
    parent: streamers
    weight: 1
    url: https://www.twitch.tv/lovesudonimh
  - name: Spicy Chicken
    identifier: neekoputkin
    parent: streamers
    weight: 2
    url: https://www.twitch.tv/neekoputkin
  - name: Aza'ela Light'nea
    identifier: azael
    parent: streamers
    weight: 3
    url: https://www.twitch.tv/azael_____
  - name: Ray Vermillion
    identifier: raiyukii
    parent: streamers
    weight: 4
    url: https://www.twitch.tv/raiyukii
  - name: DBFig
    identifier: dbfig
    parent: streamers
    weight: 5
    url: https://www.twitch.tv/dbfig
  - name: Elyria Oomori
    identifier: elyria
    parent: streamers
    weight: 5
    url: https://www.twitch.tv/elyria_oomori
